config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'static#home'

  # Static Pages
  get 'phones',    to: 'static#phones'
  get 'tos',  to: 'static#tos'
  get 'polycoms',  to: 'static#polycoms'
  get 'test',      to: 'static#test'
  get 'thankyou',  to: 'static#thankyou'
  get 'analytics',  to: 'static#analytics'
  get 'admin',  to: 'static#admin'
  get 'mail',  to: 'static#mail'

  # Scaffolds
  resources :voips
  resources :referrers
  resources :providers
  resources :resellers
  resources :internets

  # Login URLS
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Error Pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all.order('zorder ASC')
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to providers_url, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to providers_url, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :zorder)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.haml
= form_with(model: provider, local: true, class: 'container', id: 'needs-validation') do |form|

  - if provider.errors.any?
    #error_explanation.alert.alert-danger{ role: 'alert' }
      %h2
        = pluralize(provider.errors.count, "error")
        prohibited this provider from being saved:
      %ul
        - provider.errors.full_messages.each do |message|
          %li= message

  .form-group
    = form.label :name, class: 'control-label required'
    = form.text_field :name, id: :provider_name, class: 'form-control', required: true

  .form-group
    = form.label :zorder, class: 'control-label required'
    = form.number_field :zorder, id: :provider_zorder, class: 'form-control', required: true

  .form-group
    = form.submit class: 'btn btn-info btn-lg'

app/views/providers/edit.haml
%h1 Editing Provider
= render 'form', provider: @provider
= link_to 'Show', @provider
|
= link_to 'Back', providers_path

app/views/providers/index.haml
%h1 Providers

%table.table.table.table-hover
  %thead.thead-inverse
    %tr
      %th Name
      %th Order
      %th{ style: 'width: 1%; white-space: no-wrap;' }
  %tbody
    - @providers.each do |provider|
      %tr
        %td= link_to provider.name, edit_provider_path(provider)
        %td= provider.zorder
        %td{ style: 'width: 1%; white-space: nowrap;' }
          = link_to 'Edit', edit_provider_path(provider), class: 'btn btn-warning btn-sm'
          = link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'
%br/
= link_to 'New Provider', new_provider_path, class: 'btn btn-primary'

app/views/providers/new.haml
%h1 New Provider
= render 'form', provider: @provider
= link_to 'Back', providers_path

app/views/providers/show.haml
%p
  %strong Name:
  = @provider.name
= link_to 'Edit', edit_provider_path(@provider)
|
= link_to 'Back', providers_path