config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'static#home'

  # Static Pages
  get 'phones',    to: 'static#phones'
  get 'tos',  to: 'static#tos'
  get 'polycoms',  to: 'static#polycoms'
  get 'test',      to: 'static#test'
  get 'thankyou',  to: 'static#thankyou'
  get 'analytics',  to: 'static#analytics'
  get 'admin',  to: 'static#admin'
  get 'mail',  to: 'static#mail'

  # Scaffolds
  resources :voips
  resources :referrers
  resources :providers
  resources :resellers
  resources :internets

  # Login URLS
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Error Pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/internet.rb
class Internet < ApplicationRecord

  # belongs_to :provider
  # belongs_to :referrer

  # validates :provider_id, presence: true

  validates :first_name, presence: true
  validates :last_name, presence: true

  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  validates :phone, numericality: true, presence: true

  # validates :business_phone, numericality: true, presence: true

  # validates :zip, presence: true, numericality: true, length: { minimum: 5, maximum: 5 }

end

app/controllers/internets_controller.rb
class InternetsController < ApplicationController

  skip_before_action :authorize, only: [:new, :create]

  before_action :set_internet, only: [:show, :edit, :update, :destroy]

  # GET /internets
  # GET /internets.json
  def index
    @internets = Internet.all
  end

  # GET /internets/1
  # GET /internets/1.json
  def show
  end

  # GET /internets/new
  def new
    @internet = Internet.new
    @provideroptions = Provider.all.order('zorder ASC')
  end

  # GET /internets/1/edit
  def edit
    @provideroptions = Provider.all.order('zorder ASC')
  end

  # POST /internets
  # POST /internets.json
  def create
    @internet = Internet.new(internet_params)

    respond_to do |format|
      if @internet.save
        InternetMailer.welcome_email(@internet).deliver_now
        InternetMailer.new_signup_email(@internet).deliver_now
        format.html { redirect_to thankyou_path from: 'internet' }
        format.json { render :show, status: :created, location: @internet }
      else
        format.html { render :new }
        format.json { render json: @internet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /internets/1
  # PATCH/PUT /internets/1.json
  def update
    respond_to do |format|
      if @internet.update(internet_params)
        format.html { redirect_to @internet, notice: 'Internet was successfully updated.' }
        format.json { render :show, status: :ok, location: @internet }
      else
        format.html { render :edit }
        format.json { render json: @internet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /internets/1
  # DELETE /internets/1.json
  def destroy
    @internet.destroy
    respond_to do |format|
      format.html { redirect_to internets_url, notice: 'Internet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_internet
      @internet = Internet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def internet_params
      params.require(:internet).permit(:provider_id,
                                       :first_name, :last_name,
                                       :email,
                                       :phone,
                                       :best_time, :best_way,
                                       :business_name,
                                       :business_phone,
                                       :street_address_1,
                                       :street_address_2,
                                       :city, :state, :zip,
                                       :interested,
                                       :number_computers,
                                       :want_internet,
                                       :want_television,
                                       :want_phone,
                                       :number_televisions,
                                       :number_phones,
                                       :other_provider,
                                       :referrer_id,
                                       :other_referrer
                                       )
    end
end

app/helpers/internets_helper.rb
module InternetsHelper

end

app/views/internets/_form.haml
= form_with(model: internet, local: true, class: 'container', id: 'needs-validation', html: { novalidate: true } ) do |form|
  -# Show errors as needed
  - if internet.errors.any?
    #error_explanation.alert.alert-danger{ role: 'alert' }
      %h4
        = pluralize(internet.errors.count, "error")
        prohibited this internet from being saved:
      %ul
        - internet.errors.full_messages.each do |message|
          %li= message

  -# Begnining of form

  -# .form-group
  -#   = form.label :provider_id, class: 'control-label'
  -#   #isps
  -#     = form.collection_select :provider_id, Provider.all.order('zorder ASC'), :id, :name, {prompt: true}, {class: 'form-control selectpicker'}
  -#     .invalid-feedback Please provide the Business Name

  -# .form-group#otherisp.collapse.d-none
  -#   = form.label :other_provider, class: 'control-label'
  -#   = form.text_field :other_provider, id: :internet_last_name, class: 'form-control'


  -# .form-row
  -#   .from-group.col-md-4
  -#     = form.label :want_internet, class: 'form-check-label' do
  -#       = form.check_box :want_internet, id: :internet_want_internet, class: 'form-check-input'
  -#       Internet
  -#     = form.select :number_computers,
  -#                   options_for_select([ ['1-5', 1], ['6-10', 2], ['11-15', 3], ['16+', 5] ]),
  -#                   { prompt: 'Number of Computers' },
  -#                   { class: 'form-control selectpicker collapse', id: :internet_number_computers}

  -#   .from-group.col-md-4
  -#     = form.label :want_television, class: 'form-check-label' do
  -#       = form.check_box :want_television, id: :internet_want_television, class: 'form-check-input'
  -#       Television
  -#     = form.select :number_televisions,
  -#                   options_for_select([ ['1-5', 1], ['6-10', 2], ['11-15', 3], ['16+', 4] ]),
  -#                   { prompt: 'Number of Televisions' },
  -#                   { class: 'form-control selectpicker collapse', id: :internet_number_televisions}

  -#   .from-group.col-md-4
  -#     = form.label :want_phone, class: 'form-check-label' do
  -#       = form.check_box :want_phone, id: :internet_want_phone, class: 'form-check-input'
  -#       Phones
  -#     = form.select :number_phones,
  -#                   options_for_select([ ['1-5', 1], ['6-10', 2], ['11-15', 3], ['16+', 4] ]),
  -#                   { prompt: 'Number of Phones' },
  -#                   { class: 'form-control selectpicker collapse' , id: :internet_number_phones}

  -# %hr.my-5/

  .form-row
    .form-group.col-md-6
      = form.label :first_name, class: 'control-label required'
      = form.text_field :first_name, id: :internet_first_name, class: 'form-control', required: true
      .invalid-feedback Please provide your First Name
    .form-group.col-md-6
      = form.label :last_name, class: 'control-label required'
      = form.text_field :last_name, id: :internet_last_name, class: 'form-control', required: true
      .invalid-feedback Please provide your Last Name

  .form-group
    = form.label :email, class: 'control-label required'
    = form.email_field :email, id: :internet_email, class: 'form-control', required: true
    .invalid-feedback Please provide your Email Address

  .form-group
    = form.label :phone, class: 'control-label required'
    = form.telephone_field :phone, id: :internet_phone, class: 'form-control', required: true
    .invalid-feedback Please provide your Telephone Number

  .form-row
    .form-group.col-md-6
      = form.label :best_time
      = form.select :best_time,
                    options_for_select(best_times),
                    { prompt: 'Please Choose' },
                    { id: :internet_best_time, class: 'form-control selectpicker' }
    .form-group.col-md-6
      = form.label :best_way
      = form.select :best_way,
                    options_for_select(best_ways),
                    { prompt: 'Please Choose' },
                    { id: :internet_best_way, class: 'form-control selectpicker' }

  -# %hr.my-5/

  -# .form-group
  -#   = form.label :business_name, class: 'control-label required'
  -#   = form.text_field :business_name, id: :internet_business_name, class: 'form-control', required: true
  -#   .invalid-feedback Please provide the Business Name

  -# .form-group
  -#   = form.label :business_phone, class: 'control-label required'
  -#   = form.telephone_field :business_phone, id: :internet_business_phone, class: 'form-control', required: true
  -#   .invalid-feedback Please provide the Business Phone Number

  -# .form-group
  -#   = form.label :street_address_1, class: 'control-label required'
  -#   = form.text_field :street_address_1, id: :internet_street_address_1, class: 'form-control', required: true
  -#   .invalid-feedback Please provide the Business Address
  -# .form-group
  -#   = form.label :street_address_2
  -#   = form.text_field :street_address_2, id: :internet_street_address_2, class: 'form-control'

  -# .form-row
  -#   .form-group.col-md-6
  -#     = form.label :city, class: 'control-label required'
  -#     = form.text_field :city, id: :internet_city, class: 'form-control', required: true
  -#     .invalid-feedback Please provide the Business City
  -#   .form-group.col-md-3
  -#     = form.label :state, class: 'control-label required'
  -#     = form.select :state,
  -#                   options_for_select(us_states),
  -#                   { prompt: 'Please Choose' },
  -#                   { id: :internet_state, class: 'form-control selectpicker', required: true }
  -#     .invalid-feedback Please provide the Business State
  -#   .form-group.col-md-3
  -#     = form.label :zip, class: 'control-label required'
  -#     = form.text_field :zip, id: :internet_zip, class: 'form-control', required: true
  -#     .invalid-feedback Please provide the Business Zip Code

  -# .form-group.my-5
  -#   = form.label :interested, class: 'form-check-label' do
  -#     = form.check_box :interested, id: :internet_interested, class: 'form-check-input'
  -#     I Am Also Interested In A Free Telephone System


  -# .form-group.my-4
  -#   = form.label :referrer_id, 'How did you hear about FreeCableInstall.com?', class: 'control-label'
  -#   #referrers
  -#     = form.collection_select :referrer_id, Referrer.all.order('zorder ASC'), :id, :name, {include_blank: 'Please select'}, {class: 'form-control selectpicker'}

  -# .form-group#otherreferrer.collapse
  -#   = form.label :other_referrer, class: 'control-label'
  -#   = form.text_field :other_referrer, id: :internet_other_referrer, class: 'form-control'

  -# .form-group
  -#   .g-recaptcha{ 'data-sitekey': '6LelDDMUAAAAAGBBqJVyTMwgh2UpnhwhGJKR6w3d' }
  -#   -# Captcha
  -#   %script{ src: 'https://www.google.com/recaptcha/api.js' }

  .form-group.mt-5
    = form.submit 'Send Request', class: 'btn btn-info btn-lg'

app/views/internets/edit.haml
= render 'form', internet: @internet

app/views/internets/index.haml
%h1 Internets

%table.table.table-hover.w-100
  %thead.thead-inverse
    %tr
      %th ISP
      -# %th Computers
      -# %th VOIP?
      %th Name
      -# %th Email
      -# %th Phone
      -# %th Best time
      -# %th Best way
      %th Business
      -# %th Business phone
      -# %th Street address 1
      -# %th Street address 2
      -# %th Location
      -# %th Zip
      %th{ style: 'width: 1%; white-space: no-wrap;' }
  %tbody
    - @internets.each do |internet|
      %tr
        -# %td= internet.provider.name
        -# %td= internet.number_computers
        -# %td= internet.interested
        %td= link_to internet.first_name + ' ' + internet.last_name, internet
        -# %td= internet.first_name + ' ' + internet.last_name
        -# %td= mail_to internet.email
        -# %td= tel_to internet.phone
        -# %td= internet.best_time
        -# %td= internet.best_way
        %td= internet.business_name
        -# %td= internet.business_phone
        -# %td= internet.street_address_1
        -# %td= internet.street_address_2
        -# %td= internet.city + ', ' + internet.state
        -# %td= internet.zip
        %td
          -# = link_to 'Show', internet, class: 'btn btn-warning'
          -# = link_to 'Edit', edit_internet_path(internet)
          = link_to 'Destroy', internet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

app/views/internets/new.haml
- title 'Free Internet Installation'
- meta_description 'Get a full featured Voice over IP telephone system for your business free today!'
- meta_keywords 'Polycom, VVX, business media phone, Polycom phones, Polycom VVX phones, VVX 500, VVX 1500, VVX 1500D,  VVX series'
- meta_canonical 'http://freecableinstall.com/test'

.jumbotron.bg-fgreen.text-white.text-center
  %h1.display-3 Internet
  %p.lead.tandcapply Order Now:  Internet, TV, and Telephone services, from your local provider with no installation charge.

= render 'form', internet: @internet

app/views/internets/show.haml
-# = link_to 'Back', internets_path
%h1
  = @internet.provider.name + ' order for ' + @internet.first_name + ' ' + @internet.last_name
  = ' at ' + @internet.business_name unless @internet.business_name == ''

%dl.row.p-2
  - if @internet.want_internet
    %dt.col-sm-2 Computers:
    %dd.col-sm-10= @internet.number_computers
  - if @internet.want_television
    %dt.col-sm-2 Televisions
    %dd.col-sm-10=@internet.number_televisions
  - if @internet.want_phone
    %dt.col-sm-2 Phones
    %dd.col-sm-10=@internet.number_phones

%p
  Is
  = ' NOT ' unless @internet.interested
  intersested in VOIP.

%p
  Referred by
  =@internet.referrer.name

%hr/

.row
  .col-md-6
    %h2 Contact
    %ul.list-unstyled
      %li= @internet.first_name + ' ' + @internet.last_name
      %li= mail_to @internet.email
      %li= tel_to @internet.phone

      %p.mt-4= 'Best to contact by ' + @internet.best_way + ' in the ' + @internet.best_time

  .col-md-6
    %h2 Business Info
    %ul.list-unstyled
      %li= @internet.business_name
      %li= @internet.business_phone
      %li= @internet.street_address_1
      - unless  @internet.street_address_2 == ''
        %li= @internet.street_address_2
      %li= @internet.city + ', ' + @internet.state + ' ' + @internet.zip

%hr/

= link_to 'Edit', edit_internet_path(@internet), class: 'btn btn-success'
= link_to 'Destroy', @internet, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'