config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'static#home'

  # Static Pages
  get 'phones',    to: 'static#phones'
  get 'tos',  to: 'static#tos'
  get 'polycoms',  to: 'static#polycoms'
  get 'test',      to: 'static#test'
  get 'thankyou',  to: 'static#thankyou'
  get 'analytics',  to: 'static#analytics'
  get 'admin',  to: 'static#admin'
  get 'mail',  to: 'static#mail'

  # Scaffolds
  resources :voips
  resources :referrers
  resources :providers
  resources :resellers
  resources :internets

  # Login URLS
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Error Pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/referrer.rb
class Referrer < ApplicationRecord
  # has_many :internets
  # has_many :voips
end

app/controllers/referrers_controller.rb
class ReferrersController < ApplicationController
  before_action :set_referrer, only: [:show, :edit, :update, :destroy]

  # GET /referrers
  # GET /referrers.json
  def index
    @referrers = Referrer.all
  end

  # GET /referrers/1
  # GET /referrers/1.json
  def show
  end

  # GET /referrers/new
  def new
    @referrer = Referrer.new
  end

  # GET /referrers/1/edit
  def edit
  end

  # POST /referrers
  # POST /referrers.json
  def create
    @referrer = Referrer.new(referrer_params)

    respond_to do |format|
      if @referrer.save
        format.html { redirect_to @referrer, notice: 'Referrer was successfully created.' }
        format.json { render :show, status: :created, location: @referrer }
      else
        format.html { render :new }
        format.json { render json: @referrer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /referrers/1
  # PATCH/PUT /referrers/1.json
  def update
    respond_to do |format|
      if @referrer.update(referrer_params)
        format.html { redirect_to @referrer, notice: 'Referrer was successfully updated.' }
        format.json { render :show, status: :ok, location: @referrer }
      else
        format.html { render :edit }
        format.json { render json: @referrer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /referrers/1
  # DELETE /referrers/1.json
  def destroy
    @referrer.destroy
    respond_to do |format|
      format.html { redirect_to referrers_url, notice: 'Referrer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_referrer
      @referrer = Referrer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def referrer_params
      params.require(:referrer).permit(:name, :zorder)
    end
end

app/helpers/referrers_helper.rb
module ReferrersHelper
end

app/views/referrers/_form.haml
= form_with(model: referrer, local: true) do |form|
  - if referrer.errors.any?
    #error_explanation
      %h2
        = pluralize(referrer.errors.count, "error")
        prohibited this referrer from being saved:
      %ul
        - referrer.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :referrer_name
  .field
    = form.label :zorder
    = form.text_field :zorder, id: :zorder_name
  .actions
    = form.submit

app/views/referrers/edit.html.erb
<h1>Editing Referrer</h1>

<%= render 'form', referrer: @referrer %>

<%= link_to 'Show', @referrer %> |
<%= link_to 'Back', referrers_path %>

app/views/referrers/index.haml
%h1 Referrers

%table.table.table.table-hover
  %thead.thead-inverse
    %tr
      %th Name
      %th Order
      %th{ style: 'width: 1%; white-space: no-wrap;' }
  %tbody
    - @referrers.each do |referrer|
      %tr
        %td= link_to edit_referrer_path(referrer), referrer
        %td= referrer.zorder
        %td{ style: 'width: 1%; white-space: nowrap;' }
          = link_to 'Edit', edit_referrer_path(referrer), class: 'btn btn-warning btn-sm'
          = link_to 'Destroy', referrer, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'

= link_to 'New Referrer', new_referrer_path, class: 'btn btn-primary'

app/views/referrers/new.html.erb
<h1>New Referrer</h1>

<%= render 'form', referrer: @referrer %>

<%= link_to 'Back', referrers_path %>

app/views/referrers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @referrer.name %>
</p>

<%= link_to 'Edit', edit_referrer_path(@referrer) %> |
<%= link_to 'Back', referrers_path %>