config/routes.rb
Rails.application.routes.draw do

  # Homepage
  root 'static#home'

  # Static Pages
  get 'phones',    to: 'static#phones'
  get 'tos',  to: 'static#tos'
  get 'polycoms',  to: 'static#polycoms'
  get 'test',      to: 'static#test'
  get 'thankyou',  to: 'static#thankyou'
  get 'analytics',  to: 'static#analytics'
  get 'admin',  to: 'static#admin'
  get 'mail',  to: 'static#mail'

  # Scaffolds
  resources :voips
  resources :referrers
  resources :providers
  resources :resellers
  resources :internets

  # Login URLS
  get 'users/new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Error Pages
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/layouts/_meta.haml
-(0..3).each do |i|
  <!-- ================Meta Data Start================================= -->

%title
  - if yield(:title).present?
    = yield(:title)
    &bull; FreeCableInstall.com
  - else
    Free Cable Install

<!-- ================================================================== -->

- if yield(:meta_description).present?
  %meta{ name: 'description', content: yield(:meta_description) }/
- else
  %meta{ name: 'description', content: 'Complete Business Internet and Telephone (Hosted PBX) Solutions!' }/

- if yield(:meta_keywords).present?
  %meta{ content: yield(:meta_keywords), 'name': 'keywords' }/

- if yield(:meta_canonical).present?
  %link{ href: yield(:meta_canonical), rel: 'canonical' }/

<!-- ================================================================== -->

%meta{ property: 'og:locale',         content: 'en_US', }/
%meta{ property: 'og:type',           content: 'website'}/
%meta{ property: 'og:site_name',      content: 'FreeCableInstall.com' }/
%meta{ property: 'og:image',          content: '/assets/internet.jpg' }

- if yield(:meta_canonical).present?
  %meta{ property: 'og:url',          content: yield(:meta_canonical) }/

- if yield(:title).present?
  %meta{ property: 'og:title',        content: yield(:title) + ' • FreeCableInstall.com' }/

- if yield(:meta_description).present?
  %meta{ property: 'og:description',  content: yield(:meta_description) }/

<!-- ================================================================== -->

%meta{ name: 'twitter:card',          content: 'summary' }/
%meta{ name: 'twitter:site',          content: '@maxsip' }/
%meta{ name: 'twitter:creator',       content: '@maxsip' }/
%meta{ name: 'twitter:image',         content: '/assets/internet.jpg' }/

- if yield(:meta_description).present?
  %meta{ name: 'twitter:description', content: yield(:meta_description) }/

- if yield(:title).present?
  %meta{ name: 'twitter:title',       content: yield(:title) + ' • FreeCableInstall.com' }/

<!-- ================================================================== -->

%meta{ name: 'original-source', content: 'https://maxsip.com/' }/

-(0..3).each do |i|
  <!-- =======================Meta Data End============================ -->

app/views/layouts/_nav.haml
%ul.nav.justify-content-center.hidden

  - if logged_in?
    %li.nav-item.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle.text-warning{ 'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': 'dropdown', href: '#', role: 'button' }
        Internet
      .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
        %a.dropdown-item=link_to 'Internet', new_internet_path,  class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item
          =link_to internets_path,  class: 'text-warning nav-link' do
            Sign Ups
            .badge.badge-pill.badge-info= Internet.all.length
  -else
    %li.nav-item=link_to 'Internet',    new_internet_path,  class: 'text-warning nav-link'


  - if logged_in?
    %li.nav-item.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle.text-warning{ 'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': 'dropdown', href: '#', role: 'button' }
        VOIP
      .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
        %a.dropdown-item=link_to 'VOIP', new_voip_path, class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item
          =link_to voips_path, class: 'text-warning nav-link' do
            Sign Ups
            .badge.badge-pill.badge-info= Voip.all.length
  -else
    %li.nav-item=link_to 'VOIP', new_voip_path, class: 'text-warning nav-link'


  - if logged_in?
    %li.nav-item.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle.text-warning{ 'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': 'dropdown', href: '#', role: 'button' }
        Resellers
      .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
        %a.dropdown-item=link_to 'Resellers', new_reseller_path, class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item
          =link_to voips_path, class: 'text-warning nav-link' do
            Sign Ups
            .badge.badge-pill.badge-info= Reseller.all.length
  -else
    %li.nav-item=link_to 'Resellers',   new_reseller_path,     class: 'text-warning nav-link'


  - if logged_in?
    %li.nav-item.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle.text-warning{ 'aria-expanded': false, 'aria-haspopup': true, 'data-toggle': 'dropdown', href: '#', role: 'button' }
        Admin
      .dropdown-menu{ 'aria-labelledby': 'navbarDropdown' }
        -# %a.dropdown-item=link_to 'Polycoms', polycoms_path, class: 'text-warning nav-link'
        %a.dropdown-item=link_to 'Admin', admin_path, class: 'text-warning nav-link'
        %a.dropdown-item=link_to 'Thank You', thankyou_path, class: 'text-warning nav-link'
        %a.dropdown-item=link_to 'Test', test_path, class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item=link_to 'Providers', providers_path,  class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item=link_to 'Mail Lists', mail_path,  class: 'text-warning nav-link'
        .dropdown-divider
        %a.dropdown-item=link_to 'Logoff', logout_path, method: :delete, class: 'text-danger nav-link'

app/views/layouts/_partners.haml
%h1.text-center.text-secondary.mt-5.mb-3 Our Partners
%ul.d-flex.justify-content-around.flex-wrap.partners
  %li=image_tag 'logos/polycom.svg', alt: 'Polycom'
  %li=image_tag 'logos/verizon.svg', alt: 'Verizon'
  %li=image_tag 'logos/charter-spectrum.svg', alt: 'Spectrum'
  %li=image_tag 'logos/optimum.svg', alt: 'Optimum'
  %li=image_tag 'logos/att.svg', alt: 'AT&am;T'
  %li=image_tag 'logos/comcast.svg', alt: 'Comcast'
  -# %li=image_tag 'logos/centurylink.svg', alt: 'Centrury Link'
  -# %li=image_tag 'logos/cogent.svg', alt: 'Cogent'
  -# %li=image_tag 'logos/cox.svg', alt: 'Cox'
  -# %li=image_tag 'logos/frontier-auth.svg', alt: 'Frontier'
  -# %li=image_tag 'logos/lightpath.svg', alt: 'Lightpath'
  -# %li=image_tag 'logos/mediacom.svg', alt: 'Mediacom'
  -# %li=image_tag 'logos/rcn.svg', alt: 'RCN'
  -# %li=image_tag 'logos/xfinity.svg', alt: 'Xfinity'

app/views/layouts/_svglogo.haml
%svg{ version: '1.1', viewbox: '0 0 310 130', width: '310', height: '130' }
  %rect{ x: '115', y:   '5', fill: 'NONE', width: '80', height: '80', stroke: 'black', 'stroke-width': '0' }
  %g.logobox{ 'stroke-width': '5', fill: 'none' }
    %polyline{ points: '114,35  114,4  145,4', stroke: '#E9572C' }
    %polyline{ points: '165,4  196,4  196,35', stroke: '#89C138' }
    %polyline{ points: '196,55  196,86  165,86', stroke: '#4CBFD8' }
    %polyline{ points: '145,86  114,86  114,55', stroke: '#69C7B5' }
    %text.logof{ x: '142', y:  '64', fill: '#FAB30E', 'font-size': '52', 'font-weight': 'bold', 'font-family': 'roboto' } F
  %text.logoname{ x:   '6', y: '128', fill: '#FAB30E', 'font-size': '37', 'font-family': 'Crete Round', 'letter-spacing': '2px;' } Free Cable Install

app/views/layouts/application.haml
!!!
%html{ lang: 'en' }
  %head

    %meta{ charset: 'utf-8' }/
    %meta{ content: 'width=device-width, initial-scale=1, shrink-to-fit=no', name: 'viewport' }/

    -# Variable Meta Data
    = render partial: '/layouts/meta'

    -# Favicons
    %link{ href: '/favicon.ico', rel: 'icon', type: 'image/x-icon' }/

    %link{ rel: 'dns-prefetch', href: 'https://www.googletagmanager.com' }
    %link{ rel: 'dns-prefetch', href: '//fonts.googleapis.com' }

    -# Rails imports
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body

    / Google Tag Manager (noscript)
    %noscript
      %iframe{ height: 0, width: 0, src: 'https://www.googletagmanager.com/ns.html?id=GTM-MTB2KDG', style: 'display:none;visibility:hidden' }
    / End Google Tag Manager (noscript)

    %nav.fixed-top
      %header
        %h5.phonenum.sticky-top.p-1.text-left.hidden-sm-down
          Order By Phone:
          =tel_to "877.937.3306"
        .row
          .col-sm.text-center
            -# =link_to image_tag('logo2.png'), root_path
            %a{ href: '/' }= render partial: '/layouts/svglogo'
        .row.text-center
          .col-sm= render partial: '/layouts/nav'


    .container-fluid

      - if flash[:danger]
        .alert.alert-danger.alert-dismissible.fade.show{ role: 'alert' }
          = flash[:danger]
          %button.close{ 'aria-label': 'Close', 'data-dismiss': 'alert', type: 'button' }
            %span{ 'aria-hidden': true } ×

      - if notice
        .alert.alert-success{ role: 'alert' }= notice

      =yield

    .container.partners.pt-4= render partial: '/layouts/partners'

    %footer.mt-5
      .container
        %p.text-center.text-muted
          Powered by
          %a.text-info{ href: 'http://maxsip.com' } Maxsip
          &copy; |
          %a.text-info.tandcapply#tosmodalbtn{ 'data-href': '/tos', 'data-toggle': 'modal', 'data-target': '#exampleModalLong' } Terms and Condition

    / Terms and Conditions Modal
    #exampleModalLong.modal.fade{ 'aria-hidden': 'true', 'aria-labelledby': 'exampleModalLongTitle', role: 'dialog', tabindex: '-1' }
      .modal-dialog.modal-lg{ role: 'document' }
        .modal-content
          .modal-header
            %h5#exampleModalLongTitle.modal-title Terms and Conditions
            %button.close{ 'aria-label': 'Close', 'data-dismiss': 'modal', type: 'button' }
              %span{'aria-hidden': 'true' } ×
          .modal-body
          .modal-footer
            %button.btn.btn-info{ 'data-dismiss': 'modal', type: 'button' } Close

    / Global site tag (gtag.js) - Google Analytics
    %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-107489713-1"}
    :javascript
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-107489713-1');

    :javascript
      window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
      d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
      _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
      $.src="https://v2.zopim.com/?5YTR2OIl44vigQIvCQzYt8XL0jJCDCE5";z.t=+new Date;$.
      type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");